### ISSUE TITLE
Some suggestions for this project

### ISSUE THREAD

**Issue by Rotten-LKZ** [Bug-Duck/tntjs#12]
## Intro
I am very glad to see a group of junior high school students like you contribute to open source. However, there are many problems in this project that restrict the development of this project and the sustainable development of Bug Duck team. So I would like to make some suggestions and hope to adopt them.

## Problems
1. Nonstandard codes. Try reading articles on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript), which can help you learn more about JavaScript's APIs and can avoid such code:
```typescript
function prv_stringContains(char: string, s: string): boolean {
    for (const i of s) {
        if (i === char) {
            return true;
        }
    }
    return false;
}
// ...
let answer = value.value as string;
while (prv_stringContains('&', answer)) {
    answer = answer.replace('&', "&amp;");
}
while (prv_stringContains('<', answer)) {
    answer = answer.replace('<', "&lt;");
}
while (prv_stringContains('>', answer)) {
    answer = answer.replace('>', "&gt;");
}
return answer;
```
2. Make full use of GitHub. GitHub has enough features which can support Bug Duck's teamwork. So make the code on GitHub is latest version. This can make others contribute this repo better.
3. #10 The conflits in your team should not discuss in public.
4. Make commits standard. I know that members of Bug Duck are obstinate (#5). However, commits can give information about what you have changed. This can help you find which codes caused bug if there is a bug.
> By the way, commits are always like this:
> \<type\>(\<scope\>): \<subject\>
> Type includes: feat(new feature), fix(fix bugs), docs(update docs), refactor, test, chore and so on.
> Scope means scope of influence
> Subject means what a commit changed.
5. The description, website, topics of this project can be added.
6. A good library always has unit test, linter and so on. This can help the code of this repo to be more standardized and have a unified style, and less bugs.

## Conclusion
Hope this project better.

**Comment by samzhangjy** [comment]
Hi. Thank you for submitting this issue!

> Nonstandard codes. Try reading articles on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript), which can help you learn more about JavaScript's APIs and can avoid such code:

Yes. We're currently focusing on writing code in a better quality. MDN surely is a great resource for our team members to read!

> Make full use of GitHub. GitHub has enough features which can support Bug Duck's teamwork. So make the code on GitHub is latest version. This can make others contribute this repo better.

Yep I totally agree with you. We're moving our repositories from Coding to here on GitHub.

> The conflits in your team should not discuss in public.

Yes. However this should be something accident. We will try avoiding things like that in the future. 

> Make commits standard. I know that members of Bug Duck are obstinate (https://github.com/Bug-Duck/tntjs/issues/5). However, commits can give information about what you have changed. This can help you find which codes caused bug if there is a bug.

We're currently moving our commit message standard to Conventional Commit.

> A good library always has unit test, linter and so on. This can help the code of this repo to be more standardized and have a unified style, and less bugs.

We will be including those in the near future.

## Conclusion

However, the current versions of TNTjs have many problems to solve. Our team members have different experience of web development, so collaborating might be not that easy. But we'll try our best to develop and ship tntjs to the open source world.

Thank you!
