### ISSUE TITLE
删除 node_modules 上传到 git

### ISSUE THREAD

**Issue by a145789** [Bug-Duck/tntjs#2]
看到 node_modules 被传上来了，这个文件很大，而且与项目无关，可以用 [这个](https://blog.csdn.net/weixin_43294966/article/details/87479167) 删掉

**Comment by Xinlong-Wu** [comment]
确实，只要保留package.json就好了。还有就是可以新建一个doc文件夹把相关的图片资源都放进去。目录树会干净一些

**Comment by samzhangjy** [comment]
已经删除相关文件，这确实是我们的疏忽。感谢提出！
