### ISSUE TITLE
一丢丢小 tip

### ISSUE THREAD

**Issue by Leizhenpeng** [Bug-Duck/tntjs#5]
- git commit 规范一下....
- node_module 就不要上传了...
- .vscode 这类配置文件也.....
- 少点嵌套 if else
- 代码尽量可以自注释,注意一下变量命名规范.

**Comment by onion108** [comment]
ok，我们命名规范已经讨论过了，但是我们组里仍然有一些人要固执己见，我们也没办法只能让他们去了，我会坚守runtime的干净，但是别的地方我是真的没有精力去管了（领导人的代码差的一塌糊涂，根本管不了，让他来管那代码会越写越糟的）
